name: openwrt build

on:
  workflow_dispatch:
#     inputs:
#       param:
#         description: 'parameter'
#         required: false
#         default: ''

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  REPO_TAG: v22.03.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install soft
      run: sudo apt-get install mkisofs
    
    - name: info
      run: |
        whoami
        pwd
    
    - name: Check before space usage
      run: df -hT
    
    - name: git source
      run: |
        git clone $REPO_URL openwrt
        #cd openwrt
        #git checkout $REPO_TAG 
      
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
    
    - name: Load offical or custom configuration
      run: |
        cd openwrt
        wget https://downloads.openwrt.org/releases/22.03.2/targets/x86/64/config.buildinfo -O .config
        
    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        
    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=sc
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    
    - name: Check after space usage
      run: df -hT
